// Copyright 2018 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package status provides a comprehensive status tracking system for build tools.
//
// This package is responsible for:
// - Tracking various operations executed by tools (such as kati, ninja)
// - Aggregating action count information (total, running, started, finished)
// - Distributing status information to multiple output targets
// - Providing thread-safe access to shared build progress data
//
// The status system follows a pub/sub-like pattern where:
// 1. Tools report their operations through the ToolStatus interface
// 2. Status collects and aggregates these reports
// 3. Status forwards the aggregated information to all registered StatusOutput implementations
// 4. Each output can display/build upon this information as needed (terminal, file, GUI, etc.)
//
// Thread Safety:
// All exported methods on Status and toolStatus are thread-safe. They use embedded
// sync.Mutex fields to protect shared state. The mutex ensures that:
// - Only one goroutine can modify the counts at a time
// - Each StatusOutput callback is called with the lock held
// - No deadlocks occur as long as callbacks don't call back into Status methods
//
// Message Flow:
// ToolStatus.Verbose/Status/Print/Error
//
//	    |
//	    v
//	toolStatus.message()
//	    |
//	    v
//	Status.message() with lock
//	    |
//	    v
//	StatusOutput.Message() called for each output
//
// Action Flow:
// ToolStatus.StartAction()
//
//	    |
//	    v
//	toolStatus.StartAction() -> updates local counts
//	    |
//	    v -> if StartedActions > TotalActions
//	status.updateTotalActions() -> updates global counts
//	    |
//	    v
//	status.startAction() -> notifies all outputs via StartAction()
//
// ToolStatus.FinishAction()
//
//	    |
//	    v
//	toolStatus.FinishAction() -> updates local counts
//	    |
//	    v
//	status.finishAction() -> notifies all outputs via FinishAction()
package status

import (
	"sync"
	"time"
)

// Action represents a single build operation (known as an "Edge" in Ninja build system terminology).
// Each Action corresponds to a build task that needs to be executed, such as a compilation command,
// file copy operation, or any other shell command.
//
// An Action is essentially a description of a unit of work that the build system needs to perform.
// It contains metadata about inputs, outputs, and the command to execute.
type Action struct {
	// Description is a human-readable short description of the action.
	// This field is primarily used for display purposes to inform users what operation is being performed.
	// Either Description or Command (or both) should be set.
	// Example: "compile src/main.go" (NOT the full command line)
	Description string

	// Outputs is a list of output files produced by this action (optional).
	// Typically these are the target files generated by the build command,
	// but can be any arbitrary strings that identify the action's outputs.
	// Used for incremental build correctness - the build system tracks these
	// to determine if outputs need to be regenerated.
	// Example: ["main.o", "main.h"]
	Outputs []string

	// Inputs is a list of input files that this action depends on (optional).
	// These are typically the source files that the command operates on,
	// but can be any arbitrary strings that identify the action's inputs.
	// Used for determining which actions need to be re-executed when inputs change.
	// Example: ["main.go", "util.go"]
	Inputs []string

	// Command is the actual command line to execute for this action (optional).
	// This is the full command that will be passed to a shell for execution.
	// Either Description or Command (or both) should be set.
	// Example: "gcc -o main.o main.c"
	Command string

	// ChangedInputs is a list of input files that have changed since the action was last executed (optional).
	// This field is used for incremental builds to help determine which actions need to be re-run.
	// If any input files were modified, ChangedInputs will contain those modified files.
	// The build system uses this information to decide whether to skip an action
	// (if no inputs changed) or re-execute it (if some inputs changed).
	// Example: If main.go was modified, ChangedInputs might contain ["main.go"]
	ChangedInputs []string
}

// ActionResult describes the result of executing an Action.
// When an Action completes execution (either successfully or with an error),
// an ActionResult is created to record the outcome.
type ActionResult struct {
	// Action is a pointer to the original Action struct that was executed.
	// By embedding the original Action, we can correlate this result back to
	// the specific operation that was performed. This allows outputs to access
	// the action's description, inputs, outputs, and command.
	*Action

	// Output contains the command's output (typically combined stdout and stderr).
	// For actions that execute commands, this field contains the text output
	// produced by the command. This might be compiler output, shell command results,
	// or any other text generated during execution.
	// Example: Compiler warnings/errors or the output of a shell command
	Output string

	// Error is nil if the Action executed successfully.
	// If the Action failed, Error contains the specific error that occurred.
	// Check this field to determine if the operation completed without errors.
	// Example: A non-nil error if the compiler returned a non-zero exit code
	Error error

	// Stats contains performance/resource statistics for this action execution.
	// These metrics come from the operating system's resource accounting
	// and can help analyze build performance.
	Stats ActionResultStats
}

// ActionResultStats contains resource usage statistics after executing an Action.
// These statistics are derived from the operating system's process resource accounting.
// All time values are in milliseconds, and memory/IO values are in kilobytes.
type ActionResultStats struct {
	// UserTime is the CPU time spent in user mode, in milliseconds.
	// This represents the amount of time the process spent executing
	// in user-space (application code, not kernel code).
	// High user time indicates the action is CPU-bound.
	UserTime uint32

	// SystemTime is the CPU time spent in kernel mode, in milliseconds.
	// This represents the amount of time the process spent executing
	// in kernel-space (system calls, kernel code).
	// High system time indicates the action is I/O bound or makes many system calls.
	SystemTime uint32

	// MaxRssKB is the maximum resident set size (physical memory usage), in kilobytes.
	// This represents the peak amount of physical memory the process used
	// during execution. It's a good indicator of memory-intensive actions.
	MaxRssKB uint64

	// MinorPageFaults is the number of minor page faults (also called soft faults).
	// A minor page fault occurs when a process needs a page that's not in memory
	// but can be loaded from memory (already allocated) rather than from disk.
	// This is relatively inexpensive compared to major page faults.
	MinorPageFaults uint64

	// MajorPageFaults is the number of major page faults (also called hard faults).
	// A major page fault occurs when a process needs a page that must be loaded
	// from disk. This is expensive as it involves actual disk I/O.
	// High values indicate the action requires significant disk reads.
	MajorPageFaults uint64

	// IOInputKB is the total number of kilobytes read from disk.
	// This represents the total amount of data the process read from
	// all disk I/O operations. High values indicate the action is read-intensive.
	IOInputKB uint64

	// IOOutputKB is the total number of kilobytes written to disk.
	// This represents the total amount of data the process wrote to
	// all disk I/O operations. High values indicate the action is write-intensive.
	IOOutputKB uint64

	// VoluntaryContextSwitches is the number of voluntary context switches.
	// A voluntary context switch occurs when a process voluntarily gives up
	// the CPU (e.g., waiting for I/O, calling sleep, or waiting for a lock).
	// High values indicate the action frequently waits for external events.
	VoluntaryContextSwitches uint64

	// InvoluntaryContextSwitches is the number of involuntary context switches.
	// An involuntary context switch occurs when the operating system
	// forcibly removes the process from the CPU (e.g., time slice expired,
	// or a higher priority process needs the CPU).
	// High values under high system load can indicate CPU contention.
	InvoluntaryContextSwitches uint64

	// Tags is a string tag for marking or categorizing operations.
	// This can be used to identify the type of operation, target platform,
	// or any other custom classification. Tags are typically used for
	// filtering or grouping statistics in post-build analysis.
	// Example: "android", "arm64", "release", "test"
	Tags string
}

// Counts describes the count statistics for various states of actions.
// These counters track the overall progress of a build operation.
// All values are integers representing accumulated action counts.
type Counts struct {
	// TotalActions is the expected total number of actions to execute.
	// This is the total workload for the build. This number may increase or decrease
	// during the build (especially at the beginning as the build system discovers
	// more work), but it will never decrease below StartedActions.
	// This is because actions that have started must be counted in the total.
	TotalActions int

	// RunningActions is the number of actions currently being executed.
	// This equals the count of actions where StartAction has been called
	// but FinishAction has not yet been called.
	// This represents how many build tasks are running in parallel at the moment.
	RunningActions int

	// StartedActions is the total number of actions that have been started.
	// This increments by 1 each time StartAction is called.
	// This count continuously increases throughout the build until completion.
	// Once StartedActions equals TotalActions, all work has been discovered.
	StartedActions int

	// FinishedActions is the total number of actions that have completed.
	// This increments by 1 each time FinishAction is called.
	// When FinishedActions equals TotalActions, the build is complete.
	// This value, together with StartedActions, indicates build progress.
	FinishedActions int

	// EstimatedTime is the estimated completion time for the build.
	// This is calculated based on the current build rate and remaining work.
	// It provides users with an estimate of when the build will finish.
	// A zero time.Time value indicates no estimate is available.
	EstimatedTime time.Time

	// MaxParallelism is the maximum number of parallel tasks ninja can run.
	// This value is typically determined by the number of CPU cores
	// or the -j command line parameter specified by the user.
	// It limits the number of actions that can run simultaneously.
	// A value of 0 means no limit has been set.
	MaxParallelism int
}

// ToolStatus is the interface that tools use to report their operation status
// and display information through message functions.
//
// Each build tool (e.g., kati, ninja, buildtools) implements this interface
// to report build progress. The Status system manages multiple ToolStatus instances
// and aggregates their status before outputting to registered outputs.
//
// Implementation notes:
// - Each tool should call StartTool() once to get a ToolStatus instance
// - All methods on the returned interface are thread-safe
// - StartAction and FinishAction must be called in pairs for each action
// - The same Action pointer should not be reused across different ToolStatus instances
type ToolStatus interface {
	// SetTotalActions sets the expected total number of actions for this tool.
	// This number represents the total workload to display to users.
	// If the value is less than the current number of started actions,
	// the call is ignored (because we cannot reduce the count below started actions).
	// This allows the count to grow as more work is discovered.
	// For example: ninja discovers more build edges as it parses build.ninja
	SetTotalActions(total int)

	// SetEstimatedTime sets the estimated completion time for the build.
	// This is displayed to users as "estimated time remaining" or similar.
	// A zero time.Time clears any previous estimate.
	SetEstimatedTime(estimatedTime time.Time)

	// SetMaxParallelism sets the maximum parallelism (number of parallel jobs).
	// This typically corresponds to CPU core count or -j parameter.
	// The value is used to limit concurrent action execution.
	SetMaxParallelism(max int)

	// StartAction notifies the status system that an action has started execution.
	// This updates the RunningActions and StartedActions counts atomically.
	// Each action should be started only once - do not call StartAction
	// for the same *Action pointer multiple times, even if previous
	// actions using that Action have completed.
	// Each Action should only be associated with ONE ToolStatus instance.
	// If StartedActions would exceed TotalActions, TotalActions is automatically
	// extended to include the new action.
	StartAction(action *Action)

	// FinishAction reports the result of an action execution.
	// The ActionResult must contain an *Action that was previously passed to
	// StartAction on the same ToolStatus instance.
	// Do not call FinishAction twice for the same *Action - each action
	// should have exactly one StartAction and one FinishAction call.
	// This updates RunningActions (decrements) and FinishedActions (increments).
	FinishAction(result ActionResult)

	// Verbose outputs a message at the verbose level.
	// Verbose messages are not displayed on the screen but do appear
	// in detailed build logs. Use for debug information or very detailed
	// build step records that users typically don't need to see.
	// The message is prefixed with "verbose: " when logged.
	Verbose(msg string)

	// Status outputs a message at the status level.
	// Status messages may be displayed on screen but can be overwritten
	// by other status updates (e.g., progress percentage updates).
	// The complete message still appears in detailed build logs.
	// Use for displaying temporary information like the current operation.
	// The message is prefixed with "status: " when logged.
	Status(msg string)

	// Print outputs a message at the print level.
	// Print messages are displayed and retained on screen.
	// This level is used for final build results and important
	// information that should not be overwritten.
	// No prefix is added to print messages.
	Print(msg string)

	// Error outputs a message at the error level.
	// Error messages are displayed in error logs and streams.
	// Use for reporting build failures, warnings, or important errors.
	// The message is prefixed with "error: " when logged.
	Error(msg string)

	// Finish marks this tool as finished with all operations.
	// After calling Finish, do not call SetTotalActions, StartAction,
	// or FinishAction again on this ToolStatus instance.
	// This signals that the tool has completed all build tasks,
	// allowing the system to perform final aggregation and cleanup.
	// Typically called after the build tool has finished its primary work.
	Finish()
}

// MsgLevel specifies the importance level of a log message.
// Different levels determine how messages are displayed and recorded.
// Higher levels are more important and take display precedence.
// The level determines both the on-screen display behavior and the log prefix.
type MsgLevel int

// Message level constants defining log verbosity tiers.
// These are used by ToolStatus.Verbose/Status/Print/Error methods
// and determine message display behavior and log prefixes.
//
// Message Flow by Level:
// VerboseLvl -> StatusOutput.Message() with VerboseLvl (detailed log only)
// StatusLvl  -> StatusOutput.Message() with StatusLvl (temporary display, may be overwritten)
// PrintLvl   -> StatusOutput.Message() with PrintLvl (permanent display)
// ErrorLvl   -> StatusOutput.Message() with ErrorLvl (error display)
const (
	VerboseLvl MsgLevel = iota // Verbose level: log file only, not displayed on screen
	StatusLvl                  // Status level: temporary display, may be overwritten
	PrintLvl                   // Print level: permanent display, retained on screen
	ErrorLvl                   // Error level: error display
)

// Prefix returns the log prefix string for this message level.
// The prefix is prepended to messages when they are logged.
// This helps identify message importance in log files.
//
// Return values:
// - VerboseLvl returns "verbose: " - indicates verbose/debug message
// - StatusLvl returns "status: " - indicates temporary status message
// - PrintLvl returns "" (empty) - indicates important/permanent message
// - ErrorLvl returns "error: " - indicates error message
func (l MsgLevel) Prefix() string {
	switch l {
	case VerboseLvl:
		return "verbose: "
	case StatusLvl:
		return "status: "
	case PrintLvl:
		return ""
	case ErrorLvl:
		return "error: "
	default:
		panic("Unknown message level")
	}
}

// StatusOutput is the interface for receiving status information outputs.
// Implementations of this interface can receive status updates and display
// them in various ways (terminal, file, GUI, network, etc.).
//
// All methods are guaranteed to be called while the Status internal lock is held.
// This means:
//   - At most one caller is active for each output at any time
//   - The call sequence is guaranteed to be correct (start before finish, etc.)
//   - It's unsafe to call back into Status or its ToolStatus interface from
//     a callback, as this could cause deadlocks or data inconsistency
//
// Thread Safety Note:
// Because callbacks hold the Status lock, calling Status methods from within
// a callback would cause a deadlock (trying to acquire a lock already held).
// If you need to report status from an output, use a separate goroutine.
type StatusOutput interface {
	// StartAction is called whenever ToolStatus.StartAction is invoked.
	// This callback is triggered once for each action start.
	// The counts parameter contains the aggregated counts from ALL ToolStatus
	// instances, including actions that have already finished.
	// This is an incremental update notification - the action has just started.
	// Use counts to display current build progress.
	StartAction(action *Action, counts Counts)

	// FinishAction is called whenever ToolStatus.FinishAction is invoked.
	// This callback is triggered once for each action completion.
	// The counts parameter contains the aggregated counts from ALL ToolStatus
	// instances, including this just-finished action.
	// This is a completion notification - use the result to report success/failure.
	// The result contains the action output, error, and statistics.
	FinishAction(result ActionResult, counts Counts)

	// Message is called for any message output from ToolStatus.Verbose/Status/Print/Error.
	// This is the equivalent of ToolStatus message methods, but the level
	// is passed as a parameter rather than being tied to the method name.
	// The level determines how the message should be displayed
	// and determines the prefix (if any) to add.
	Message(level MsgLevel, msg string)

	// Flush is called when output should be flushed or closed.
	// No further output will be sent after this call.
	// Use for cleanup operations like closing file handles,
	// flushing buffers, or releasing resources.
	// After Flush returns, the Status instance should no longer be used.
	Flush()

	// Write implements the io.Writer interface.
	// Allows StatusOutput to be used as a standard io.Writer
	// for I/O redirection, log file writing, etc.
	// The Write method should handle the standard write semantics.
	Write(p []byte) (n int, err error)
}

// Status acts as a multiplexer/accumulator between ToolStatus instances
// (obtained via StartTool) and StatusOutput instances (added via AddOutput).
//
// Typically there is one Status instance per build process.
// However, tools like multiproduct_kati may have multiple independent
// Status instances (one per product being built).
//
// Architecture Overview:
//
// ┌─────────────────────────────────────────────────────────────────────┐
// │                         Status                                     │
// │  ┌─────────────────────────────────────────────────────────────┐  │
// │  │ counts: Counts          outputs: []StatusOutput              │  │
// │  │ maxParallelism: int   lock: sync.Mutex                    │  │
// │  └─────────────────────────────────────────────────────────────┘  │
// └─────────────────────────────────────────────────────────────────────┘
//
//	     |                    |
//	     |                    |
//	     v                    v
//	toolStatus           StatusOutput
//	(per tool)          (multiple)
//	     |                    |
//	     | (notifies)        |
//	     +------------------+
//
// Operation Flow:
//
//  1. Create Status instance
//  2. Add StatusOutput(s) via AddOutput()
//  3. For each tool:
//     a. Get ToolStatus via StartTool()
//     b. Tool reports actions/-progress via ToolStatus methods
//     c. Status aggregates and forwards to all outputs
//  4. Call Finish() when done
//
// Thread Safety Mechanism:
//
// The Status uses an embedded sync.Mutex for thread safety:
//   - All public methods lock the mutex before accessing shared state
//   - All StatusOutput callbacks are made while holding the lock
//   - Each output callback is called sequentially (not concurrently)
//   - The lock prevents data races on counts and outputs slice
//
// This design ensures:
//   - Counters are updated atomically
//   - Outputs receive consistent count snapshots
//   - No data races between goroutines
//
// Message Flow From ToolStatus to StatusOutput:
//
//  1. Tool calls toolStatus.Verbose("message")
//  2. toolStatus.message(VerboseLvl, "message") is invoked
//  3. toolStatus acquires its local lock (for safety)
//  4. Calls status.message() with the message
//  5. status.message() acquires the status lock
//  6. For each output in status.outputs:
//     output.Message(VerboseLvl, "message")
//  7. Each output.Message() is called with lock held
//  8. Output handles display/logging appropriately
//
// Action Flow From ToolStatus to StatusOutput:
//
//  1. Tool calls toolStatus.StartAction(action)
//  2. toolStatus.StartAction() updates local counts with lock
//  3. If StartedActions > TotalActions, update TotalActions
//  4. Calls status.startAction(action)
//  5. status.startAction() acquires lock
//  6. Updates global RunningActions and StartedActions
//  7. For each output in outputs:
//     output.StartAction(action, counts)
//  8. Each output.StartAction() is called with lock held
//
//  9. Later, tool calls toolStatus.FinishAction(result)
//  10. toolStatus.FinishAction() updates local counts with lock
//  11. Calls status.finishAction(result)
//  12. status.finishAction() acquires lock
//  13. Updates global RunningActions--, FinishedActions++
//  14. For each output:
//     output.FinishAction(result, counts)
type Status struct {
	// counts stores the aggregated count statistics for all actions.
	// This includes totals from all ToolStatus instances.
	// Protected by lock.
	counts Counts

	// outputs stores all registered StatusOutput implementations.
	// Each output receives all status updates and messages.
	// Protected by lock.
	outputs []StatusOutput

	// maxParallelism stores the current maximum parallelism setting.
	// This is typically set from the -j command line parameter
	// or auto-detected from CPU core count.
	// Protected by lock.
	maxParallelism int

	// lock protects counts and outputs fields.
	// This mutex ensures thread-safe access to shared state.
	// ALL public methods acquire this lock before accessing fields.
	// ALL StatusOutput callbacks are made while holding this lock.
	// This design ensures outputs receive consistent snapshots
	// and prevents data races in multi-threaded scenarios.
	// Never call this lock from within a StatusOutput callback
	// as it would cause a deadlock.
	lock sync.Mutex
}

// AddOutput attaches an output receiver to this Status instance.
// Each StatusOutput will receive all status updates and messages.
//
// Typically an output should only be attached to one Status instance.
// If nil is passed, the call has no effect (no-op).
//
// Common output implementations:
// - Terminal status display (progress bar, current action)
// - Log file writer
// - Remote progress reporter (for distributed builds)
// - GUI status display
func (s *Status) AddOutput(output StatusOutput) {
	if output == nil {
		return
	}

	s.lock.Lock()
	defer s.lock.Unlock()

	s.outputs = append(s.outputs, output)
}

// StartTool returns a new ToolStatus implementation for a tool to report status.
// Each tool should call StartTool exactly once to get its own ToolStatus interface.
// The returned interface is actually an internal toolStatus struct.
//
// Usage:
//
//	status := status.New()
//	tool1 := status.StartTool()
//	tool2 := status.StartTool()
//	// tool1 and tool2 are independent, each tracks their own counts
//	// but both report to the same outputs
//
// The returned ToolStatus is thread-safe and can be used from multiple goroutines.
func (s *Status) StartTool() ToolStatus {
	return &toolStatus{
		status: s,
	}
}

// Finish flushes all outputs and performs final cleanup.
// This should be called when the build is complete.
//
// After calling Finish:
// - No further methods should be called on this Status instance
// - No further methods should be called on any associated ToolStatus instances
// - All outputs will have their Flush() method called
//
// This signals that the build process has fully ended and allows
// outputs to perform final cleanup (close files, release resources, etc.).
func (s *Status) Finish() {
	s.lock.Lock()
	defer s.lock.Unlock()

	for _, o := range s.outputs {
		o.Flush()
	}
}

// updateTotalActions updates the total action count.
// This is an internal method that modifies the global TotalActions count.
// The diff parameter is the amount to add (which can be negative).
// This method acquires the lock, so it should only be called when
// the caller doesn't already hold the lock.
//
// This method is used to synchronize TotalActions between toolStatus
// local counts and the global Status counts.
func (s *Status) updateTotalActions(diff int) {
	s.lock.Lock()
	defer s.lock.Unlock()

	s.counts.TotalActions += diff
}

// SetEstimatedTime sets the estimated completion time.
// This updates the EstimatedTime field in the counts.
// This time is displayed to users as the expected finish time.
func (s *Status) SetEstimatedTime(estimatedTime time.Time) {
	s.lock.Lock()
	defer s.lock.Unlock()

	s.counts.EstimatedTime = estimatedTime
}

// SetMaxParallelism sets the maximum parallel task count.
// This value limits how many actions can run simultaneously.
// It is typically set from the -j parameter or auto-detected.
func (s *Status) SetMaxParallelism(max int) {
	s.lock.Lock()
	defer s.lock.Unlock()

	s.maxParallelism = max
}

// startAction notifies the status system that an action has started.
// This is an internal method that updates counters and notifies outputs.
// It increments RunningActions (currently running) and StartedActions (total started).
// Each output receives a StartAction callback with the action and current counts.
func (s *Status) startAction(action *Action) {
	s.lock.Lock()
	defer s.lock.Unlock()

	s.counts.RunningActions += 1
	s.counts.StartedActions += 1
	s.counts.MaxParallelism = s.maxParallelism

	// Notify all outputs that an action has started
	// Each output receives the action and current aggregated counts
	for _, o := range s.outputs {
		o.StartAction(action, s.counts)
	}
}

// finishAction notifies the status system that an action has completed.
// This is an internal method that updates counters and notifies outputs.
// It decrements RunningActions and increments FinishedActions.
// Each output receives a FinishAction callback with the result and current counts.
func (s *Status) finishAction(result ActionResult) {
	s.lock.Lock()
	defer s.lock.Unlock()

	s.counts.RunningActions -= 1
	s.counts.FinishedActions += 1
	s.counts.MaxParallelism = s.maxParallelism

	// Notify all outputs that an action has finished
	// Each output receives the result and current aggregated counts
	for _, o := range s.outputs {
		o.FinishAction(result, s.counts)
	}
}

// message sends a message to all outputs at a specified level.
// This is an internal method that distributes messages to outputs.
// The level determines the message prefix and display behavior.
// Each output receives a Message callback with the level and message.
func (s *Status) message(level MsgLevel, msg string) {
	s.lock.Lock()
	defer s.lock.Unlock()

	// Notify all outputs of the message
	// Each output receives the message at the specified level
	for _, o := range s.outputs {
		o.Message(level, msg)
	}
}

// Status sends a status-level message to all outputs.
// Status-level messages are temporary and may be overwritten by later updates.
// Use for displaying current operation information.
func (s *Status) Status(msg string) {
	s.message(StatusLvl, msg)
}

// toolStatus is the internal implementation of the ToolStatus interface.
// Each tool that calls StartTool() received an independent toolStatus instance.
// It maintains local counts and forwards operations to the associated Status instance.
//
// Design:
// - Each toolStatus maintains its own local Counts
// - Local counts track that tool's actions separately
// - When actions start/finish, local counts are updated first
// - Then the changes are synchronized to the global Status
// - This allows multiple tools to report to the same outputs
//
// Thread Safety:
// - The local lock protects local count updates
// - The status lock protects global state updates
// - Both locks are acquired in a consistent order to prevent deadlocks
type toolStatus struct {
	// status is a reference to the parent Status instance.
	// All global state updates are forwarded through this reference.
	// This field is set once during construction and never changes.
	status *Status

	// counts maintains local count statistics for this tool.
	// These counts track only this tool's actions.
	// They are kept separate from other tools' counts.
	// Protected by lock.
	counts Counts

	// lock protects the counts field from concurrent access.
	// This mutex ensures thread-safe updates to local counts.
	// All methods on toolStatus acquire this lock before
	// accessing the counts field.
	lock sync.Mutex
}

// Compile-time assertion ensuring toolStatus implements ToolStatus.
// If this line causes a compile error, toolStatus is missing required methods.
var _ ToolStatus = (*toolStatus)(nil)

// SetTotalActions sets the expected total number of actions for this tool.
// If the new total is greater than or equal to StartedActions AND
// different from the current TotalActions, the difference is calculated
// and synchronized to the global Status.
// If the new total is less than StartedActions, the call is ignored
// (cannot reduce total below started count).
func (d *toolStatus) SetTotalActions(total int) {
	diff := 0

	d.lock.Lock()
	// Only update if new total >= started count AND different from current
	if total >= d.counts.StartedActions && total != d.counts.TotalActions {
		diff = total - d.counts.TotalActions
		d.counts.TotalActions = total
	}
	d.lock.Unlock()

	// Synchronize the difference to global Status
	if diff != 0 {
		d.status.updateTotalActions(diff)
	}
}

// SetEstimatedTime sets the estimated completion time.
// This is delegated to the associated Status instance.
func (d *toolStatus) SetEstimatedTime(estimatedTime time.Time) {
	d.status.SetEstimatedTime(estimatedTime)
}

// SetMaxParallelism sets the maximum parallelism.
// This is delegated to the associated Status instance.
func (d *toolStatus) SetMaxParallelism(max int) {
	d.status.SetMaxParallelism(max)
}

// StartAction notifies that an action has started execution.
// This updates local RunningActions and StartedActions.
// If StartedActions exceeds TotalActions, TotalActions is automatically extended.
// Then the global Status is notified of the action start.
//
// Automatic TotalActions Extension:
// If more actions are started than originally expected,
// TotalActions is automatically increased to match StartedActions.
// This handles cases where the exact number of build actions
// isn't known until the build actually runs.
func (d *toolStatus) StartAction(action *Action) {
	totalDiff := 0

	d.lock.Lock()
	d.counts.RunningActions += 1
	d.counts.StartedActions += 1

	// If started actions exceed expected total, auto-extend total
	if d.counts.StartedActions > d.counts.TotalActions {
		totalDiff = d.counts.StartedActions - d.counts.TotalActions
		d.counts.TotalActions = d.counts.StartedActions
	}
	d.lock.Unlock()

	// Sync to global status
	if totalDiff != 0 {
		d.status.updateTotalActions(totalDiff)
	}
	// Notify global status that action has started
	d.status.startAction(action)
}

// FinishAction reports that an action has completed execution.
// This updates local RunningActions (decrements) and FinishedActions (increments).
// Then the global Status is notified of the action completion.
func (d *toolStatus) FinishAction(result ActionResult) {
	d.lock.Lock()
	d.counts.RunningActions -= 1
	d.counts.FinishedActions += 1
	d.lock.Unlock()

	d.status.finishAction(result)
}

// Verbose outputs a verbose-level message.
// This is delegated to the associated Status instance.
// Verbose messages are logged but not displayed on screen.
func (d *toolStatus) Verbose(msg string) {
	d.status.message(VerboseLvl, msg)
}

// Status outputs a status-level message.
// This is delegated to the associated Status instance.
// Status messages are displayed temporarily and may be overwritten.
func (d *toolStatus) Status(msg string) {
	d.status.message(StatusLvl, msg)
}

// Print outputs a print-level message.
// This is delegated to the associated Status instance.
// Print messages are displayed permanently.
func (d *toolStatus) Print(msg string) {
	d.status.message(PrintLvl, msg)
}

// Error outputs an error-level message.
// This is delegated to the associated Status instance.
// Error messages are displayed as errors.
func (d *toolStatus) Error(msg string) {
	d.status.message(ErrorLvl, msg)
}

// Finish marks this tool as finished with all operations.
// If TotalActions differs from StartedActions, TotalActions is adjusted.
// RunningActions is reset to 0, and TotalActions is set to StartedActions.
// This ensures the final counts are consistent.
//
// Final Adjustments:
// - If TotalActions != StartedActions, the difference is synced to global Status
// - RunningActions is set to 0 (all actions have finished)
// - TotalActions is set to StartedActions (final count matches actual work)
// This method should be called when a tool completes all its work.
func (d *toolStatus) Finish() {
	d.lock.Lock()
	defer d.lock.Unlock()

	// Ensure total matches actual started count
	if d.counts.TotalActions != d.counts.StartedActions {
		d.status.updateTotalActions(d.counts.StartedActions - d.counts.TotalActions)
	}

	// TODO: update status to correct running/finished edges?
	d.counts.RunningActions = 0
	d.counts.TotalActions = d.counts.StartedActions
}
