// Copyright 2024 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ninja_writer

import (
	"strings"
	"testing"
)

func TestEmptyFile(t *testing.T) {
	nf := &NinjaFile{}
	var b strings.Builder
	_, err := nf.WriteTo(&b)
	if err != nil {
		t.Fatalf("WriteTo failed: %v", err)
	}
	if b.String() != "" {
		t.Errorf("empty file should produce empty output, got %q", b.String())
	}
}

func TestComments(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddComment("Generated by bootstrap")
	nf.AddComment("")
	nf.AddComment("Stage 1: build ninja_mod")

	got := mustRender(t, nf)
	// Empty comment produces a bare newline (visual separator)
	if !strings.HasPrefix(got, "# Generated by bootstrap\n") {
		t.Errorf("first comment missing, got:\n%s", got)
	}
	if !strings.Contains(got, "# Stage 1: build ninja_mod") {
		t.Errorf("second comment missing, got:\n%s", got)
	}
}

func TestVariables(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddVariable("cxx", "g++")
	nf.AddVariable("cflags", "-O2 -Wall")

	got := mustRender(t, nf)
	if !strings.Contains(got, "cxx = g++\n") {
		t.Errorf("missing cxx variable, got:\n%s", got)
	}
	if !strings.Contains(got, "cflags = -O2 -Wall\n") {
		t.Errorf("missing cflags variable, got:\n%s", got)
	}
}

func TestPool(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddPool("link_pool", 4)

	got := mustRender(t, nf)
	want := "pool link_pool\n  depth = 4\n"
	if !strings.Contains(got, want) {
		t.Errorf("pool mismatch, got:\n%s", got)
	}
}

func TestRuleMinimal(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddRule(Rule{
		Name:    "cxx",
		Command: "$cxx $cflags -c $in -o $out",
	})

	got := mustRender(t, nf)
	want := "rule cxx\n  command = $cxx $cflags -c $in -o $out\n\n"
	if got != want {
		t.Errorf("rule mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestRuleFull(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddRule(Rule{
		Name:        "cxx",
		Command:     "$cxx -MMD -MT $out -MF $out.d $cflags -c $in -o $out",
		Description: "CXX $out",
		Depfile:     "$out.d",
		Deps:        "gcc",
		Restat:      true,
		Variables: []Variable{
			{"extra", "-Werror"},
		},
	})

	got := mustRender(t, nf)
	lines := strings.Split(got, "\n")

	assertLine(t, lines, "rule cxx")
	assertLine(t, lines, "  command = $cxx -MMD -MT $out -MF $out.d $cflags -c $in -o $out")
	assertLine(t, lines, "  description = CXX $out")
	assertLine(t, lines, "  depfile = $out.d")
	assertLine(t, lines, "  deps = gcc")
	assertLine(t, lines, "  restat = true")
	assertLine(t, lines, "  extra = -Werror")
}

func TestBuildBasic(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddBuild(Build{
		RuleName: "cxx",
		Outputs:  []string{"build/foo.o"},
		Inputs:   []string{"src/foo.cc"},
	})

	got := mustRender(t, nf)
	want := "build build/foo.o: cxx src/foo.cc\n"
	if !strings.Contains(got, want) {
		t.Errorf("build edge mismatch, got:\n%s", got)
	}
}

func TestBuildWithImplicitsAndOrderOnly(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddBuild(Build{
		RuleName:  "link",
		Outputs:   []string{"build/ninja_mod"},
		Inputs:    []string{"build/ninja.o"},
		Implicits: []string{"build/libninja.a"},
		OrderOnly: []string{"build/stamp"},
	})

	got := mustRender(t, nf)
	want := "build build/ninja_mod: link build/ninja.o | build/libninja.a || build/stamp\n"
	if !strings.Contains(got, want) {
		t.Errorf("build edge with deps mismatch, got:\n%s", got)
	}
}

func TestBuildWithVariables(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddBuild(Build{
		RuleName:  "link",
		Outputs:   []string{"build/ninja_mod"},
		Inputs:    []string{"build/ninja.o"},
		Implicits: []string{"build/libninja.a"},
		Variables: []Variable{
			{"libs", "-lpthread"},
		},
	})

	got := mustRender(t, nf)
	if !strings.Contains(got, "build build/ninja_mod: link build/ninja.o | build/libninja.a\n") {
		t.Errorf("missing build edge, got:\n%s", got)
	}
	if !strings.Contains(got, "  libs = -lpthread\n") {
		t.Errorf("missing libs variable, got:\n%s", got)
	}
}

func TestBuildWithPool(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddBuild(Build{
		RuleName: "link",
		Outputs:  []string{"build/ninja_mod"},
		Inputs:   []string{"build/ninja.o"},
		Pool:     "link_pool",
	})

	got := mustRender(t, nf)
	if !strings.Contains(got, "  pool = link_pool\n") {
		t.Errorf("missing pool, got:\n%s", got)
	}
}

func TestMultipleOutputs(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddBuild(Build{
		RuleName: "generate",
		Outputs:  []string{"build/a.h", "build/a.cc"},
		Inputs:   []string{"src/a.proto"},
	})

	got := mustRender(t, nf)
	if !strings.Contains(got, "build build/a.h build/a.cc: generate src/a.proto\n") {
		t.Errorf("multiple outputs mismatch, got:\n%s", got)
	}
}

func TestDefaults(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddDefault("build/ninja_mod")
	nf.AddDefault("build/ninja_monitor")

	got := mustRender(t, nf)
	if !strings.Contains(got, "default build/ninja_mod build/ninja_monitor\n") {
		t.Errorf("defaults mismatch, got:\n%s", got)
	}
}

func TestFullNinjaFile(t *testing.T) {
	nf := &NinjaFile{}
	nf.AddComment("Stage 1: build ninja_mod from source")
	nf.AddVariable("cxx", "g++")
	nf.AddVariable("cflags", "-O2 -Wall -Wextra -Wno-deprecated -fno-rtti -pthread")

	nf.AddRule(Rule{
		Name:        "cxx",
		Command:     "$cxx -MMD -MT $out -MF $out.d $cflags -c $in -o $out",
		Description: "CXX $out",
		Depfile:     "$out.d",
		Deps:        "gcc",
	})

	nf.AddRule(Rule{
		Name:        "ar",
		Command:     "rm -f $out && ar crs $out $in",
		Description: "AR $out",
	})

	nf.AddRule(Rule{
		Name:        "link",
		Command:     "$cxx -o $out $in $libs",
		Description: "LINK $out",
	})

	nf.AddBuild(Build{
		RuleName: "cxx",
		Outputs:  []string{"$builddir/build.o"},
		Inputs:   []string{"$src/build.cc"},
	})

	nf.AddBuild(Build{
		RuleName: "ar",
		Outputs:  []string{"$builddir/libninja.a"},
		Inputs:   []string{"$builddir/build.o"},
	})

	nf.AddBuild(Build{
		RuleName:  "link",
		Outputs:   []string{"$builddir/ninja_mod"},
		Inputs:    []string{"$builddir/ninja.o"},
		Implicits: []string{"$builddir/libninja.a"},
		Variables: []Variable{
			{"libs", "-L$builddir -lninja -lpthread"},
		},
	})

	got := mustRender(t, nf)

	// Verify structure ordering: comments → variables → rules → builds
	commentIdx := strings.Index(got, "# Stage 1")
	varIdx := strings.Index(got, "cxx = ")
	ruleIdx := strings.Index(got, "rule cxx")
	buildIdx := strings.Index(got, "build $builddir/build.o:")

	if !(commentIdx < varIdx && varIdx < ruleIdx && ruleIdx < buildIdx) {
		t.Errorf("section ordering wrong: comment=%d var=%d rule=%d build=%d",
			commentIdx, varIdx, ruleIdx, buildIdx)
	}
}

func mustRender(t *testing.T, nf *NinjaFile) string {
	t.Helper()
	var b strings.Builder
	_, err := nf.WriteTo(&b)
	if err != nil {
		t.Fatalf("WriteTo failed: %v", err)
	}
	return b.String()
}

func assertLine(t *testing.T, lines []string, want string) {
	t.Helper()
	for _, l := range lines {
		if l == want {
			return
		}
	}
	t.Errorf("line %q not found in output lines: %v", want, lines)
}
